_id: c67a5650-76f9-11e7-a3e9-cb63094aa20f
metadata:
  author: Larry Aagesen
  github_id: laagesen
  email: Larry.Aagesen@inl.gov
  simulation_name: inl_moose_6a
  summary: >-
    Benchmark problem 6a, energy vs time. 160 x 160 uniform mesh, iteration
    adaptive time stepping, target iterations=8
  timestamp: '26 July, 2017'
  implementation:
    repo:
      url: 'https://github.com/dschwen/CHiMaD_Hackathon'
      version: 4b543d98c423fa719d360c16edf70960477c09d7
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: multiprocessing
    clock_rate: '2.7'
    cores: '8'
    nodes: '1'
  software:
    name: moose
    version: ''
    repo:
      url: 'https://github.com/idaholab/moose'
      version: 6e33f5a4bfddd4a5c951ba493a87526c91509bfa
benchmark:
  id: 6a
  version: '0'
data:
  - name: free_energy
    url: 'https://gist.githubusercontent.com/laagesen/d8ed181db58d77625336461c21f989b3/raw/9e5679ea74730616d7ee39fb7900a00e1bcc02a6/problem2a_out_160_dtIA8_upload.csv'
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - as: y
        expr: datum.free_energy
        type: formula
      - as: x
        expr: datum.time
        type: formula
    description: Free Energy Plot
    type: line
  - name: run_time
    values:
      - wall_time: '495'
        sim_time: '400'
  - name: memory_usage
    values:
      - unit: B
        value: '800000000'
date: 1501620081
