_id: a76de900-76f6-11e7-a3e9-cb63094aa20f
metadata:
  author: David Montiel
  github_id: "david-montiel-t"
  email: dmontiel@umich.edu
  simulation_name: prismspf_6a_flux_med
  summary: >-
    Solution to the 6a benchmark problem with an intermediate level of
    refinement.  Run on PRISMS dedicated hardware at the University of
    Michigan's Flux supercomputing cluster.
  timestamp: '28 July, 2017'
  implementation:
    repo:
      url: >-
        https://github.com/prisms-center/phaseField/tree/v2.0pre/applications/cahnHilliard_electrostatics
      version: 8a75a0f27bc157430f7fbe623265c120724d9ce5
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: multiprocessing
    clock_rate: '2.6'
    cores: '16'
    nodes: '2'
  software:
    name: prisms
    version: 2.0pre
    repo:
      url: 'https://github.com/prisms-center/phaseField/tree/v2.0pre'
      version: 8a75a0f27bc157430f7fbe623265c120724d9ce5
benchmark:
  version: '0'
  id: 6a
data:
  - name: free_energy
    url: https://gist.githubusercontent.com/wd15/23c6f2d74c4c41d8da883feee30efdee/raw/12633176adddfb4375c780cfa10678d251520d3d/energy_6a.csv
    format:
      parse:
        Time: number
        Energy: number
      type: csv
    transform:
      - as: y
        expr: datum.Energy
        type: formula
      - as: x
        expr: datum.Time
        type: formula
    type: line
    description: Free Energy Plot
  - name: run_time
    values:
      - wall_time: '507'
        sim_time: '400'
  - name: memory_usage
    values:
      - unit: KB
        value: '124000'
date: 1501618740
