metadata:
  author: Jon Guyer
  email: guyer@nist.gov
  github_id: guyer
  simulation_name: fipy_6b_macbookpro
  summary: Serial benchmark with FiPy on Gmsh mesh with round right
  timestamp: '1 August, 2017'
  implementation:
    repo:
      url: 'https://github.com/guyer/hackathonIII'
      version: 0b52c55d
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '2.9'
    cores: '1'
    nodes: '1'
  software:
    name: fipy
    version: 3.1.3.dev167+g8b4ec87c
    repo:
      url: 'https://github.com/usnistgov/fipy'
      version: ecbe868f2aff6
benchmark:
  version: '0'
  id: 6b
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/wd15/9986ba35b6dfef5bdffef15db52de547/raw/ccb55df9b1a4d5b826fd4a8bb09c666336ad8d1c/energy.txt
    format:
      parse:
        time: number
        free_energy: number
      type: dsv
      delimiter: ' '
    transform:
      - as: y
        expr: datum.free_energy
        type: formula
      - as: x
        expr: datum.time
        type: formula
    description: Free Energy Plot
    type: line
  - name: run_time
    values:
      - wall_time: '4350'
        sim_time: '1000'
  - name: memory_usage
    values:
      - unit: KB
        value: '266000'
date: 1501621688
