benchmark:
  id: 1c
  version: 1
data:
- name: timestep
  values: 0.00104167
- format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/93af8ee482b5a66b04ff7284e61ef716/raw/c4b4e8c606a8fe209d7a0ea42e4267f3c53056e2/mmsp_1c_raspi_results.csv
- name: run_time
  values:
  - sim_time: 4166.67
    wall_time: 200039.81
- name: memory_usage
  values:
  - unit: KB
    value: 8596
metadata:
  author:
    first: Trevor
    last: Keller
  email: trevor.keller@nist.gov
  github_id: tkphd
  hardware:
    architecture: armv7l
    cores: 18
    details:
    - name: clock
      values: 1.2
  implementation:
    details:
    - name: mesh
      values: uniform rectilinear
    - name: numerical_method
      values: explicit finite difference
    - name: compiler
      values: GNU mpic++
    - name: parallel_model
      values: MPI
    end_condition: 4000000 time steps
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 8be003758f9d1d4ee2f1e3ccaeec3a16199a0c62
  software:
    name: mmsp
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 8f29eb47146b9fbbdcd17b08d12e06fceb3ed728
    version: '5.2'
  summary: Raspberry Pi 3 cluster benchmark with MMSP, T-shape domain
  timestamp: Tue, 07 Feb 2017 22:13:26 +0000
