benchmark:
  id: 1b
  version: 1
data:
- name: timestep
  values: 0.00104167
- format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1b_wrksttn.csv
- name: run_time
  values:
  - sim_time: 53333.3
    wall_time: 170618.87
- name: memory_usage
  values:
  - unit: KB
    value: 28492
metadata:
  author: Trevor Keller
  email: trevor.keller@nist.gov
  github_id: tkphd
  hardware:
    architecture: x86_64
    cores: 12
    details:
    - name: clock
      values: 3.8
  implementation:
    details:
    - name: mesh
      values: uniform rectilinear
    - name: numerical_method
      values: explicit finite difference
    - name: compiler
      values: GNU mpic++
    - name: parallel_model
      values: MPI
    end_condition: sim time greater than 50000 (51200000 timesteps)
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/no-flux/
      version: 4c3af04ac4e46665eacc599b0d2cc8b4a9963461
  software:
    name: mmsp
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 2352cdf62c6db99f6644d88a0c2f9917d2d1882f
    version: '5.2'
  summary: MPI parallel workstation benchmark with MMSP, no-flux domain
  timestamp: Sun, 12 Feb 2017 09:16:30 -0500
