benchmark:
  id: 1c
  version: 1
data:
- name: timestep
  values: 0.00195312
- name: free_energy
  transform:
  - as: free_energy
    expr: datum.energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - energy: 31.8815
    time: 0
  - energy: 31.7653
    time: 7.61719
  - energy: 31.3578
    time: 15.2344
  - energy: 29.8382
    time: 22.8516
  - energy: 26.3998
    time: 30.4688
  - energy: 23.095
    time: 38.0859
  - energy: 21.4502
    time: 45.7031
  - energy: 20.4617
    time: 53.3203
  - energy: 19.8369
    time: 60.9375
  - energy: 19.3948
    time: 68.5547
  - energy: 19.0146
    time: 76.1719
- name: run_time
  values:
  - sim_time: 19.0146
    wall_time: 189.44
- name: memory_usage
  values:
  - unit: KB
    value: 32504
metadata:
  author: Trevor Keller
  email: trevor.keller@nist.gov
  github_id: tkphd
  hardware:
    architecture: x86_64
    cores: 2
    details:
    - name: clock
      values: 2300.0
  implementation:
    details:
    - name: mesh
      values: uniform rectilinear
    - name: numerical_method
      values: explicit finite difference
    - name: compiler
      values: GNU mpic++
    - name: parallel_model
      values: MPI
    end_condition: time limit, Travis CI runs die after 50 minutes total
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 05a5db5111d92b916d51e143adf068547c3a654d
  software:
    name: mmsp
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 8f29eb47146b9fbbdcd17b08d12e06fceb3ed728
    version: '5.2'
  summary: Parallel Travis CI benchmark with MMSP, T-shape domain
  timestamp: Tue, 10 Jan 2017 01:40:01 +0000
